name: ifohack_spatial_py310
channels:
  - conda-forge
dependencies:
  - access=1.1.8
  - affine=2.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alembic=1.10.4
  - amply=0.1.5
  - aom=3.5.0
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-auth=0.6.26
  - aws-c-cal=0.5.21
  - aws-c-common=0.8.14
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.6
  - aws-c-io=0.13.19
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.8
  - aws-c-sdkutils=0.1.9
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.9
  - aws-requests-auth=0.4.2
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - beautifulsoup4=4.12.2
  - blinker=1.6.2
  - blosc=1.21.3
  - boltons=23.0.0
  - boost-cpp=1.78.0
  - boto3=1.26.114
  - botocore=1.29.115
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.8.0
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.1
  - charset-normalizer=2.1.1
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - conda=23.3.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - configparser=5.3.0
  - contourpy=1.0.7
  - cryptography=40.0.2
  - curl=8.0.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.4.0
  - databricks-cli=0.17.6
  - dav1d=1.0.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - deprecated=1.2.13
  - deprecation=2.1.0
  - descartes=1.1.0
  - docker-py=6.0.0
  - docutils=0.19
  - earthengine-api=0.1.349
  - entrypoints=0.4
  - esda=2.4.3
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.5.0
  - flask=2.2.3
  - fmt=9.1.0
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.3
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - gdal=3.6.3
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giddy=2.3.4
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glib=2.76.1
  - glib-tools=2.76.1
  - glog=0.6.0
  - glpk=5.0
  - google-api-core=2.11.0
  - google-api-python-client=2.85.0
  - google-auth=2.17.3
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.8.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.4.1
  - googleapis-common-protos=1.57.1
  - greenlet=2.0.2
  - grpcio=1.52.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - httplib2=0.22.0
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.27.0
  - importlib-metadata=6.4.1
  - importlib_metadata=6.4.1
  - importlib_resources=5.12.0
  - inequality=1.0.0
  - iniconfig=2.0.0
  - intel-openmp=2023.0.0
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipywidgets=8.0.6
  - itsdangerous=2.1.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jsonlines=1.2.0
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.17.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.7
  - jxrlib=1.1
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.2
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libarrow=11.0.0
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcurl=8.0.1
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.6.3
  - libglib=2.76.1
  - libgoogle-cloud=2.8.0
  - libgrpc=1.52.1
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libmamba=1.4.2
  - libmambapy=1.4.2
  - libnetcdf=4.9.1
  - libogg=1.3.4
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - libpysal=4.7.0
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.2.4
  - mamba=1.4.2
  - mapclassify=2.5.0
  - markdown=3.4.3
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - menuinst=1.4.19
  - mgwr=2.1.2
  - mkl=2023.0.0
  - mlflow=2.3.0
  - momepy=0.5.4
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nodejs=18.15.0
  - numba=0.56.4
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openpyxl=3.1.1
  - openssl=3.1.0
  - orc=1.8.3
  - packaging=23.1
  - palettable=3.3.2
  - pandas=2.0.0
  - paramiko=3.1.0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - pluggy=1.0.0
  - ply=3.11
  - pointpats=2.3.0
  - pooch=1.7.0
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.1
  - prometheus_client=0.16.0
  - prometheus_flask_exporter=0.22.3
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pulp=2.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pygeos=0.14
  - pygments=2.15.0
  - pyjwt=2.6.0
  - pynacl=1.5.0
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysal=23.1
  - pysocks=1.7.1
  - pytest=7.3.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10=3_cp310
  - pytz=2023.3
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pywin32=304
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - quantecon=0.5.3
  - querystring_parser=1.2.4
  - quilt3=5.3.0
  - rasterio=1.3.6
  - re2=2023.02.02
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - requests-futures=1.0.0
  - rsa=4.9
  - rtree=1.0.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - rvlib=0.0.6
  - s3transfer=0.6.0
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - segregation=2.3.1
  - setuptools=67.6.1
  - shap=0.41.0
  - shapely=2.0.1
  - simplejson=3.19.1
  - sip=6.7.8
  - six=1.16.0
  - slicer=0.0.7
  - smmap=3.0.5
  - snappy=1.1.10
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - spaghetti=1.7.2
  - spglm=1.0.8
  - spint=1.0.7
  - splot=1.1.5.post1
  - spopt=0.5.0
  - spreg=1.3.2
  - spvcm=0.3.0
  - spyder-kernels=2.4.3
  - sqlalchemy=2.0.10
  - sqlite=3.40.0
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tenacity=8.2.2
  - threadpoolctl=3.1.0
  - tifffile=2023.4.12
  - tiledb=2.13.2
  - tk=8.6.12
  - tobler=0.9.0
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - uritemplate=4.1.1
  - urllib3=1.26.15
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - waitress=2.1.2
  - wcwidth=0.2.6
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - win_inet_pton=1.1.0
  - wrapt=1.15.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.8.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - bokeh==3.1.0
      - bqplot==0.12.39
      - colour==0.1.5
      - eerepr==0.0.4
      - fiona==1.8.22
      - future==0.18.3
      - geemap==0.20.6
      - geocoder==1.38.1
      - ipyevents==2.0.1
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.17.2
      - ipytree==0.2.2
      - osmnx==1.3.0
      - plotly==5.14.1
      - pyperclip==1.8.2
      - python-box==7.0.1
      - rasterstats==0.18.0
      - ratelim==0.1.6
      - rioxarray==0.14.1
      - scooby==0.7.1
      - traittypes==0.2.1
      - xarray==2023.4.0 
