name: ifo_tasks
dependencies:
  - numpy == 1.23.*
  - pandas == 1.5.*
  - scikit-learn == 1.2.*
  - matplotlib == 3.7.*
  - conda-forge::mlflow == 1.2.*
  - pytest == 7.1.*
  - jupyter == 1.0.*
  - notebook == 6.5.*
  - sqlite == 3.41.*
  - pip
  - pip:
      - PyDrive==1.3.1
      - drive==0.3.2
